# Site settings
# title: Mahtab
twitter_username: mahtabgol
# name: Mahtab Ghamsari

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
  - title: GitHub
    url: https://github.com/mghamsar
  - title: LinkedIn
    url: https://www.linkedin.com/in/mahtabghamsari

#Any buzzword skills you want to include
skills:
  - Python
  - Docker
  - Flask & Django
  - Hadoop & HIVE
  - Microservices
  - ReactJS
  - Product Management
  - API design
  - Data Engineering
  - Audio Signal Processing
  - Javascript
  - SQL
  - REST
  - Technical Architecture
  - Machine Learning
  - Max/MSP

#Blogfeed is optional - including this will add JS to call the feed and populate blog list
#blogfeed: https://automateddeveloper.blogspot.com/feeds/posts/default?alt=json

#Work experience is required
roles:
  - title: AI Scientist
    start: 2018
    end: 2019
    employer: Hypersurfaces, Mogees Ltd
    description: Using sensor-fusion and deep learning we turn physical objects into interactive controllers. I work both as a scientist and a product designer and scrum master. As a small team, everyone is involved with design decisions, development and research regardless of their background.
  - title: Co-Founder
    start: 2016
    end: 2018
    employer: VRSUS
    description: We're showcasing live music in Virtual Reality, integrating the most realistic elements of light, 3D sound, 360 video capture together within VR to give remote spectators a realistic sense of what it's like to actually participate in large concerts and public events.
  - title: Full-stack Engineer
    start: 2017
    end: 2018
    employer: Kheiron Medical 
    description: We're using the latest research in deep learning to help radiologists detect cancerous tumours more rapidly. My work consists of everything from web-app development to data and image processing. Our current toolset consists of python, docker, MySQL, Django, Flask, Redis, Celery and Tensorflow.
  - title: Big Data Engineer
    start: 2015
    end: 2016
    employer: Bandsintown Group
    description: Implementing the lambda architecture to take the concert-going experience to a global level. Being a small team we take on multiple tasks with multiple language requirements. While mostly focused on data pipelining, I also develop data analytics dashboards and a data service API. Working with Hadoop, Hive, Solr, AWS and programming in Java, PHP and Javascript.
  - title: Full-stack Engineer
    start: 2014
    end: 2015
    employer: Dailymotion
    description: Developing new features to optimize the online advertising experience on Dailymotion.com and its partner sites, including both In-stream and display ads. Working in AngularJS, Go and mongoDB for one project and PHP/Javascript for the site as a whole. Developing various tools to manage rules, inventory, audience targeting and reporting on online ads.

#Education is required
education:
  - level: Master of Arts (M.A.)
    date: 2012
    subject: Music Technology
    school: McGill University
  - level: Bachelor of Applied Science (B.A.Sc.)
    date: 2010
    subject: Systems Design Engineering
    school: University of Waterloo

additionalinfo:
  - Docker: Most of the projects I have lately worked on are dockerized and use an array of services and containers to run both in development mode and in production
  - Python: I have experience with both scientific python and python web framceworks such as Django and Flask
  - Cloud Platforms: I have primarily used AWS for running production apps on the cloud. I have experience setting up, configuring and running applications using a range of AWS offerings, including EC2, RDS, S3, Cogito
  - Web Development: Through building web applications, I have also worked with various client side technology, having used jQuery, Bootstrap. More recently I have written React applications
  - Development Control: I have a good knowledge of application life-cycle management and have worked with SVN, Git, Jenkins, etc. I have experience with an array of testing tools and technologies

#This section is optional (as is the image link below)
#coursera:
   #profileurl: https://www.coursera.org/user/i/c6362b4056f755a04bef6a791a62102b
   #courses:
   # - title: Functional Programming Principles in Scala
   #   link: https://www.coursera.org/course/progfun
   #   optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/progfun/small-icon.hover.png
   #   date: September 16, 2013
   # - title: Algorithms Design and Analysis, Part 1
   #   link: https://www.coursera.org/specializations/algorithms
   #   optionalimage: https://d1z850dzhxs7de.cloudfront.net/topics/algo/small-icon.hover.png
   #   date: April 28, 2014

#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
#speakerdeck:
#   profileurl: https://speakerdeck.com/robhinds
#   talks:
#    - title: Product Management for Engineers
#      speakerdeckId: 94f0070c4e434ec79fe9b4eb2cb574e0
#      conference: API Conference, Berlin 2018
#    - title: Agile Machine Learning - from Theory to Production
#      speakerdeckId: ec84f2f56e9743afb0675b1eeeb6b6ce
#      conference: W-JAX Conference, Munich 2017 (London 2017)

#List of interesting Github repo/projects to include - optional
#github:
# - robhinds/robhinds.github.io
# - robhinds/ScaLambda
# - robhinds/opinionated-akka-http
# - robhinds/food2vec
# - robhinds/microservices
# - robhinds/spring-social-geeklist
# - robhinds/spring-social-stackoverflow
# - robhinds/genotype
# - robhinds/footweets
# - robhinds/ElasticSearchGradle

#Stackoverflow flair is optional
#stackoverflow:
#   profileurl: http://stackoverflow.com/users/258813/rhinds
#   flairimageurl: http://stackoverflow.com/users/flair/258813.png

intro: I'm an engineer, entrepreneur and music/arts enthusiast currently working on transforming how we interact with the digital world through using every day objects as interfaces. My previous project VRSUS is a creative application for capturing live music in Virtual Reality and re-creating the concert experience. My other projects have involved pipelines for machine learning, concert recommendation tools, integrations for online advertising and various small web projects. I studied Systems Design and HCI in the context of music. My MA thesis presented methods and studies used in mapping live performance (human) gestures to sound in digital musical instruments. 


theme: jekyll-theme-minimal